channels:
  - conda-forge

dependencies:
  - python=3.9.13
  - pip=22.1.2
  - pip:
      #- rpaframework==15.7.0
      - rpaframework-15.8.0-py3-none-any.whl
      - rpaframework_core-9.1.1-py3-none-any.whl
      - selenium==4.4.0
      - robotframework-seleniumlibrary==6.0.0
